// gemini/multimodal-live-api/native-audio-websocket-demo-apps/ai-wealth-advisor/src/frontend/app/page.tsx
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

"use client"

import { useRouter } from "next/navigation";
import StatusBar from "@/components/StatusBar";
import { NotificationBanner } from "@/components/notification-banner";

export default function HomePage() {
  const router = useRouter();

  const handleLoginRedirect = () => {
    const notificationText = "You have a CD maturing, log in for more information.";
    router.push(`/loading?notification_text=${encodeURIComponent(notificationText)}`);
  };

  return (
    <div className="home-page-container bg-gradient-to-br from-zinc-900 to-black">
      <StatusBar />
      
      {/* Abstract background pattern */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-[-10%] right-[-10%] w-[500px] h-[500px] rounded-full bg-blue-900/20 blur-3xl"></div>
        <div className="absolute bottom-[-10%] left-[-10%] w-[500px] h-[500px] rounded-full bg-purple-900/10 blur-3xl"></div>
      </div>

      <div
        className="absolute bottom-[300px] w-full flex justify-center z-10"
      >
        <NotificationBanner onClick={handleLoginRedirect} />
      </div>
    </div>
  );
}

// gemini/sample-apps/quickbot/document-search-using-agent-builder/frontend/src/app/app.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component} from '@angular/core';
import {Router, NavigationEnd, Event as NavigationEvent} from '@angular/router';
import {UserService} from './services/user/user.service';
import {AuthService} from './services/login/auth.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'pac-assist-ui';
  showHeader = true;
  userInfo: any;

  constructor(
    private router: Router,
    private userService: UserService,
    public authService: AuthService
  ) {
    this.router.events.subscribe((event: NavigationEvent) => {
      if (event instanceof NavigationEnd) {
        if (
          event.url === '/login' ||
          event.url === '/login/e2e' ||
          (event.url.includes('login') && event.url.includes('email')) ||
          (event.url.includes('login') && event.url.includes('tos')) ||
          event.url.includes('reset-password') ||
          event.url.includes('support-ticket')
        ) {
          this.showHeader = false;
        } else {
          this.userInfo = this.userService.getUserDetails();
          this.showHeader = true;
        }
      }
    });
  }
}
